version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=GMT-6
      - PGTZ=GMT-6
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./back-end:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  
  frontend:
    container_name: frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    volumes:
      - ./front-end:/app:cached
      - /app/node_modules
    ports:
      - "3000:3000" 
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
    env_file:
      - ./.env.dev
    stdin_open: true
    tty: true
